OrderMyFood/WebRazor/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrderMyFood.Web.WebRazor.Models
{
    public class Menu
    {
        public string RestaurantName { get; set; }
        public string MenuName { get; set; }
        public decimal Price { get; set; }
        public int MenuId { get; set; }
    }
}

OrderMyFood/WebRazor/Models/RatingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrderMyFood.Web.WebRazor.Models
{
    public class RatingViewModel
    {
        public string Name { get; set; }

        public int Star { get; set; }
    }
}

OrderMyFood/WebRazor/Models/Restaurant.cs
namespace OrderMyFood.Web.WebRazor.Models
{
    public class Restaurant
    {
        public int RestaurantId { get; set; }

        public string Name { get; set; }
        public string Location { get; set; }
        public int Distance { get; set; }
        public string Cuisine { get; set; }
        public decimal Budget { get; set; }
        public short Ratings { get; set; }

    }
}

OrderMyFood/WebRazor/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebRazor.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

OrderMyFood/WebRazor/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebRazor.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

OrderMyFood/WebRazor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OrderMyFood/WebRazor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebRazor.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

OrderMyFood/WebRazor/Pages/Menu.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OrderMyFood.Web.WebRazor.Business;
using OrderMyFood.Web.WebRazor.Models;

namespace WebRazor.Pages
{
    public class MenuModel : PageModel
    {
        private readonly IRestaurantService _restService;

        public MenuModel(IRestaurantService restService)
        {

            _restService = restService;
        }
        #region UI Controls
        [BindProperty(SupportsGet = true)]
        public string PassRestaurant { get; set; }
        [BindProperty]
        public IEnumerable<SelectListItem> RestaurantViewer { get; set; }
        public IEnumerable<Menu> Menus { get; set; }
        #endregion

        #region Table Pagination
        [BindProperty(SupportsGet = true)]
        public int CurrentPage { get; set; } = 1;
        public int Count { get; set; }
        public int PageSize { get; set; } = 3;

        public int TotalPages => (int)Math.Ceiling(decimal.Divide(Count, PageSize));

        public bool ShowPrevious => CurrentPage > 1;
        public bool ShowNext => CurrentPage < TotalPages;
        public bool ShowFirst => CurrentPage != 1;
        public bool ShowLast => CurrentPage != TotalPages;
        #endregion

        public async Task OnGetAsync()
        {
           await PopulateData();
        }

        private async Task PopulateData()
        {
            IEnumerable<Restaurant> data =  await _restService.GetAllRestaurants();
            RestaurantViewer = data.Select(i => new SelectListItem()
            {
                Value = i.RestaurantId.ToString(),
                Text = i.Name,
            });
        }

        public async Task OnPost()
        {
            int restaurantId = 0;
            if (int.TryParse(PassRestaurant, out restaurantId))
            {
                Menus = await _restService.GetPaginatedResultOfMenu(restaurantId, CurrentPage, PageSize);
                Count = Menus.Count();
            }
            await PopulateData();
            ViewData["IsTableVisible"] = true;
        }

    }
}

OrderMyFood/WebRazor/Pages/Order.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

using OrderMyFood.Web.WebRazor.Data;
using OrderMyFood.Web.WebRazor.Models;

namespace WebRazor.Pages
{
    public class OrderModel : PageModel
    {


        [ViewData]
        public bool FoodItemsVisibility { get; set; }

        public void OnGet()
        {
            
        }
        public IActionResult OnGetLoadFoodPartial(string restId)
        {
            IEnumerable<Menu> resultset;
            Menu getFood;
            using (var context = new RestaurantContext())
            {
                var param= new SqlParameter("@RestId", Convert.ToInt32(restId));
                resultset = context.foodMenus.FromSql($"GetFoodByRestaurant @RestId", param);
                //resultset = context.Database.ExecuteSqlCommand("GetFoodByRestaurant @RestId", param);
                getFood = (from o in resultset select new Menu { MenuId = o.MenuId, MenuName = o.MenuName, Price = o.Price }).FirstOrDefault();
                           
            }           
            return new JsonResult(getFood);
        }

        public void OnPostCustomer(Customer customer)
        {
            
        }

        public void OnPostRestaurant()
        {
            var restId = Request.Form["restaurant"];
        }
        #region ViewModel Objects
        public class Customer
        {
            [BindProperty]
            public string Name { get; set; }

            [BindProperty]
            public string Email { get; set; }

            [BindProperty]
            public decimal Amount { get; set; }

            [BindProperty]
            public string Address { get; set; }

        }

        [BindProperty]
        public Food food { get; set; }

        public class Food
        {

            [BindProperty(SupportsGet = true)]
            public int FoodId { get; set; }

            [BindProperty(SupportsGet = true)]
            public string FoodName { get; set; }

            [BindProperty(SupportsGet = true)]
            public decimal Price { get; set; }

        }
        #endregion
    }
}

OrderMyFood/WebRazor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebRazor.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

OrderMyFood/WebRazor/Pages/Rating.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OrderMyFood.Web.WebRazor.Business;
using Microsoft.AspNetCore.Authorization;
using OrderMyFood.Web.WebRazor.Models;

namespace WebRazor.Pages
{
    public class RatingModel : PageModel
    {
        private readonly IReviewService _restService;

        public RatingModel(IReviewService restService)
        {

            _restService = restService;
        }

        public IEnumerable<RatingViewModel> ratingViewModel { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SubmittedRating { get; set; }

       
        public async Task OnGet()
        {
           ratingViewModel = await _restService.GetRatings();
        }

        public void OnPostUpdateRating(string name, string value)
        {
            //
        }

        public void OnPost()
        {
            var store = Request.Form["SubmittedRating"];
        }
    }

}

OrderMyFood/WebRazor/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebRazor.Pages
{
    public class RegisterModel : PageModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }

        public void OnGet()
        {
        }
    }
}

OrderMyFood/WebRazor/Pages/Restaurant.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using OrderMyFood.Web.WebRazor.Business;
using OrderMyFood.Web.WebRazor.Models;

namespace WebRazor.Pages
{
    public class RestaurantModel : PageModel
    {
        //private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IRestaurantService _restService;

        public RestaurantModel(IRestaurantService restService)
        {
            
            _restService = restService;
        }

        #region Table Pagination
        [BindProperty(SupportsGet = true)]
        public int CurrentPage { get; set; } = 1;
        public int Count { get; set; }
        public int PageSize { get; set; } = 3;

        public int TotalPages => (int)Math.Ceiling(decimal.Divide(Count, PageSize));

        public bool ShowPrevious => CurrentPage > 1;
        public bool ShowNext => CurrentPage < TotalPages;
        public bool ShowFirst => CurrentPage != 1;
        public bool ShowLast => CurrentPage != TotalPages;
        #endregion

        #region UI Controls
        [BindProperty(SupportsGet = true)]
        public string SelectedType { get; set; }
        [BindProperty]
        public IEnumerable<SelectListItem> SearchType { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchParameter { get; set; }

        [BindProperty(SupportsGet = true)]
        public string PassRestaurant { get; set; }
        [BindProperty]
        public IEnumerable<SelectListItem> RestaurantViewer { get; set; }

        public IEnumerable<Menu> Menus { get; set; }
        public List<Restaurant> Data { get; set; }
        #endregion

        [Authorize]
        public async Task OnGetAsync()
        {
            
            Data = await _restService.GetPaginatedResult(CurrentPage, PageSize);
            Count = Data.Count();
            await PopulateData();
        }

        private async Task PopulateData()
        {
            var arrayList = new System.Collections.ArrayList();
            new Restaurant().GetType().GetProperties().ToList().ForEach(l =>
            {
                if (l.Name != "RestaurantId") arrayList.Add(l.Name);
            });
            SearchType = new SelectList(arrayList);

            IEnumerable<Restaurant> data = await _restService.GetAllRestaurants();
            RestaurantViewer = data.Select(i => new SelectListItem()
            {
                Value = i.RestaurantId.ToString(),
                Text = i.Name,
            });
        }

        public async Task OnPost()
        {
            Data =  await _restService.GetRestaurantList(SelectedType, SearchParameter);
            Count = Data.Count();
            await PopulateData();
        }

        public async Task<IActionResult> OnPostMenuByRestaurant() //[FromBody] JObject jobject
        {
            int restaurantId = 0;
            await OnPost();
            if (int.TryParse(PassRestaurant, out restaurantId))
            {
                Menus = await _restService.GetOrderByRestaurant(restaurantId);
                return Page();
            }
            else
                return Page();
        }

       
    }
}

OrderMyFood/WebRazor/Pages/SignIn.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebRazor.Pages
{
    public class SignInModel : PageModel
    {
        [Authorize]
        public async Task<IActionResult> OnGet()
        {
            var user = User as ClaimsPrincipal;

            var token = await HttpContext.GetTokenAsync("access_token");
            var idToken = await HttpContext.GetTokenAsync("id_token");
            foreach (var claim in user.Claims)
            {
                Debug.WriteLine($"Claim Type: {claim.Type} - Claim Value : {claim.Value}");
            }

            if (token != null)
            {
                ViewData["access_token"] = token;

            }
            if (idToken != null)
            {

                ViewData["id_token"] = idToken;
            }
            // "Catalog" because UrlHelper doesn't support nameof() for controllers
            // https://github.com/aspnet/Mvc/issues/5853
            return RedirectToPage("/Index");
        }
    }
}

OrderMyFood/WebRazor/Pages/SignOut.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebRazor.Pages
{
    public class SignOutModel : PageModel
    {
        public async Task<IActionResult> OnGet()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);

            ////// "Catalog" because UrlHelper doesn't support nameof() for controllers
            ////// https://github.com/aspnet/Mvc/issues/5853
            var homeUrl = "/Index"; //Url.Action(nameof(CatalogController.Index), "Catalog");
            return new SignOutResult(OpenIdConnectDefaults.AuthenticationScheme,
                new AuthenticationProperties { RedirectUri = homeUrl });
        }
    }
}

OrderMyFood/WebRazor/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

OrderMyFood/WebRazor/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OrderMyFood/WebRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

OrderMyFood/WebRazor/Pages/Menu.cshtml
@page
@model WebRazor.Pages.MenuModel
@{
    ViewData["Title"] = "Restaurant App";
}
<environment include="Development">

</environment>

<h3>Menu Items</h3>
<form class="form-horizontal" method="post">
    <div class="col-md-2 col-md-offset-1">
        <select class="form-control" asp-for="PassRestaurant" asp-items="Model.RestaurantViewer"></select>
    </div>
    <div class="col-md-2 col-md-offset-1">
        @Html.AntiForgeryToken()
        <input id="load" type="submit" value="View Menu" class="btn btn-default" />
    </div>
    <div class="row">

    </div>
</form>
@if (ViewData["IsTableVisible"] != null && (bool)ViewData["IsTableVisible"] == true)
{
    <table id="tblMenu" class="table table-striped">
        <thead>
            <tr>
                <th>RestaurantName</th>
                <th>MenuID</th>
                <th>MenuName</th>
                <th>Price</th>
            </tr>
        </thead>
        @foreach (var item in Model.Menus)
        {
            <tr>
                <td>@item.RestaurantName</td>
                <td>@item.MenuId</td>
                <td>@item.MenuName</td>
                <td>@item.Price</td>
            </tr>
        }
    </table>
    <div>
        <ul class="pagination">
            <li class="page-item @(!Model.ShowFirst? "disabled":"")">
                <a asp-page="/Restaurant" asp-route-CurrentPage="1" class="page-link"><i class="glyphicon glyphicon-fast-backward"></i></a>
            </li>

            <li class="page-item @(!Model.ShowPrevious? "disabled":"")">
                <a asp-page="/Restaurant" asp-route-CurrentPage="@(Model.CurrentPage -1)" class="page-link"><i class="glyphicon glyphicon-step-backward"></i></a>
            </li>
            <li class="page-item  @(!Model.ShowNext? "disabled":"")">
                <a asp-page="/Restaurant" asp-route-CurrentPage="@(Model.CurrentPage + 1)" class="page-link"><i class="glyphicon glyphicon-step-forward"></i></a>
            </li>

            <li class="page-item  @(!Model.ShowLast? "disabled":"")">
                <a asp-page="/Restaurant" asp-route-CurrentPage="@Model.TotalPages" class="page-link"><i class="glyphicon glyphicon-fast-forward"></i></a>
            </li>
        </ul>
    </div>
}

OrderMyFood/WebRazor/Pages/Order.cshtml
@page
@model WebRazor.Pages.OrderModel
@{
    <style type="text/css">
        .txtBoxWidth {
            width: 90px;
        }

        .setMarginAll {
            margin: 15px 10px;
        }
    </style>
    <form method="post">
        <div class="row">

            <div class="setMarginAll col-md-offset-1 col-md-4">
                <select id="restaurant" name="restaurant">
                    <option value="">Select a number</option>
                    <option value="1">Barbequnation</option>
                    <option value="2">Paradize</option>
                    <option value="4">Mango Tree</option>
                    <option value="5">Brewsky</option>
                </select>
                <hr />
                <input id="getMenu" type="submit" value="GetMenu" class="btn btn-default" onclick="loadFood()" />
                @*asp-page-handler="restaurant"*@
                <hr />

                <div id="menulist" class="form-horizontal">
                    <input id="foodId" class="txtBoxWidth setMarginAll" type="text" asp-for="food.FoodId" />
                    <input id="foodName" class="txtBoxWidth setMarginAll" type="text" asp-for="food.FoodName" />
                    <input id="foodPrice" class="txtBoxWidth setMarginAll" type="text" asp-for="food.Price" />
                </div></div>
            <div class="col-md-offset-1 col-md-4">
                <div class="form-horizontal">
                    <input type="text" class="txtBoxWidth setMarginAll" id="Name" name="Name" value="" />
                    <input type="text" class="txtBoxWidth setMarginAll" data-val="true" data-val-email="The Email field is not a valid e-mail address." id="Email" name="Email" value="" />
                    <input type="number" class="txtBoxWidth setMarginAll" data-val="true" data-val-required="Amount is required." id="Amount" name="Amount" value="" />
                    <textarea data-val="true" class="txtBoxWidth setMarginAll" data-val-maxlength-max="300" id="Address" name="Address"></textarea>
                </div>
                <hr />
                <input type="submit" value="Submit" class="btn btn-default" width="60" asp-page-handler="customer" />
            </div>

            <div class="col-md-2"></div>
        </div>
    </form>
    @section scripts{
        <script>
            function loadFood() {
                var pass = $("#restaurant option:selected").val();
                //console.log(pass);
                $.ajax({
                    type: 'GET',
                    url: 'Order?handler=LoadFoodPartial',
                    contentType: 'application/json',
                    data: { 'restId' : pass},
                    dataType: 'JSON',
                    success: function (response) {
                        debugger;
                        console.log(response.d);
                        $(".txtBoxWidth").show();
                        $("#foodId").val(response.d[0].FoodId);
                        $("#foodName").val(response.d[0].FoodName);
                        $("#foodPrice").val(response.d[0].FoodPrice);

                    },
                    failure: function (err) {
                        console.log(err);
                    }
                });
            }



            $(function () {
                $(".txtBoxWidth").hide();
        });
        </script>
    }
}

OrderMyFood/WebRazor/Pages/Register.cshtml
@page
@model WebRazor.Pages.RegisterModel
@{
}
<div class="row">
    <div class="col-md-4">
        <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
            <h4>Register with Social Account</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-default">Register</button>
        </form>
    </div>
</div>

OrderMyFood/WebRazor/Pages/SignIn.cshtml
@page
@model WebRazor.Pages.SignInModel
@{
}

OrderMyFood/WebRazor/Pages/SignOut.cshtml
@page
@model WebRazor.Pages.SignOutModel
@{
}